### ISSUE TITLE
about Resnet18_8s

### ISSUE THREAD

**Issue by MahlerMozart** [warmspringwinds/pytorch-segmentation-detection#1]
Hello, I am very impressed by your great work! However, I am a little confused when I look at your Resnet18_8s network. I assume Resnet18_8s follows your approach in your paper "Deep Residual Learning for Instrument Segmentation in Robotic Surgery", which employ dilated convolutions to keep resolution. But in resnet_dilated.py, I could not find any dilated convolutions in Class Resnet18_8s. Could you please give more detailed explanation on the structure of Resnet18_8s? Many thanks.

**Comment by warmspringwinds** [comment]
Hi, @MahlerMozart .

For this repository we use a custom fork of pytorch/vision where we add
dilated convolutions.

Look here:
https://github.com/warmspringwinds/vision/blob/fully_conv_resnet/torchvision/models/resnet.py

I will update the front page Readme to better show that.

**Comment by MahlerMozart** [comment]
@warmspringwinds Perfect explanation. Thanks!
