### ISSUE TITLE
No such file or directory: 'resnet_34_8s_66.pth'

### ISSUE THREAD

**Issue by akashgoyal** [warmspringwinds/pytorch-segmentation-detection#5]
Hi @warmspringwinds 
I am getting - **IOError: [Errno 2] No such file or directory: 'resnet_34_8s_66.pth'**
when running **resnet_34_8s_demo.ipynb**

Not able to figure out when and how the model will generate. Any clue on the next step .

Thanks
Akash

**Comment by warmspringwinds** [comment]
Hi @akashgoyal ,
Download the respective file from a dropbox link here
https://github.com/warmspringwinds/pytorch-segmentation-detection#deeplab-semantic-image-segmentation-with-deep-convolutional-nets-atrous-convolution-and-fully-connected-crfs

Let me know if you have any further complications.

**Comment by akashgoyal** [comment]
Great !! Thank you so much :)

**Comment by akashgoyal** [comment]
@warmspringwinds 
I am still getting that error. I am not able to figure out from where the code is trying to read model. Can you please also specify where the model has to be placed ?

Thanks

**Comment by warmspringwinds** [comment]
Hi,

place it at the same directory where you are running the ipython notebook
or specify the full absolute path to your model file -- also make sure that
you specified the name of the file correctly.

2018-01-11 12:11 GMT-05:00 Akash <notifications@github.com>:

**Comment by akashgoyal** [comment]
Specifying absolute path worked for me. Thanks a ton.

**Comment by warmspringwinds** [comment]
You are welcome :)
