### ISSUE TITLE
adaptive_computation_time

### ISSUE THREAD

**Issue by hftsai** [warmspringwinds/pytorch-segmentation-detection#8]
Hi Daniil,
I'm trying to work on image segmentation of microscopy images using pytorch. 
I've been trying to work with your examples. 
But i'm having error on resnet_34_8s_train. 

> ImportError: No module named adaptive_computation_time

I wonder if it's something in the anaconda?

**Comment by warmspringwinds** [comment]
Hi @hftsai that's a bug -- feel free to remove the line:
```
from adaptive_computation_time import ACT_Module
```

I will update the repo later with this change.

**Comment by warmspringwinds** [comment]
Resolved in the latest commit, details here:
https://github.com/warmspringwinds/pytorch-segmentation-detection/pull/6
